### ISSUE TITLE
Basic RAG setup

### ISSUE THREAD

**Issue by getnamo** [getnamo/Llama-Unreal#17]
Enable feeding in data into a memory DB and vector embed it. Use a small and simple vector search to support RAG lookup of info. Potentially structure various chunking and search strategies. Likely a secondary model link to embedding model for vectorization.

## Tasks
- [x] Add llama.cpp embedding support (b5122 is definitely new enough)
- [x] Use embedding.cpp example to write `GetPromptEmbeddings` function
- [x] Test a simple header only c lib for vector search e.g. hnsw
- [x] Verify embedding works as intended with `GetPromptEmbeddings`
- [x] Add chunker
- [x] Test chunking a large text set
- [x] Vector search API scaffold to feed ~1024 dim vector
- [x] Search chunked large text
- [x] Merge hnsw branch
- [x] BM25 search
- [x] Hybrid mode
- [x] Combined rag store api
- [x] Combined component with upgraded API
- [x] Consistent fetch results (~~ban early EOS~~ prefill assistant reply)

**Comment by getnamo** [comment]
#### Resources:

- memory db c lib: https://github.com/facebookresearch/faiss/blob/main/c_api/INSTALL.md
- using embedding model to generate vectors: https://github.com/ggerganov/llama.cpp/blob/ceb/bert/examples/embedding/embedding.cpp already built in support for Bert style embedders.
- NB best results are achieved if we combine with something like a normal search (matches exact text which is a weakness of vector searches) e.g. using bm25 algorithm: https://github.com/scorta/BM25

**Comment by getnamo** [comment]
Another interesting approach: https://arxiv.org/html/2412.06078v1

**Comment by getnamo** [comment]
being tackled in: https://github.com/getnamo/Llama-Unreal/tree/feat-hnswlib

Picking hnswlib for vector search and in-built llama.cpp functionality for embedding models. More work needed for full loop tests. Added tasks to description for tracking.

**Comment by getnamo** [comment]
Embedding looks good, but vectordb in testing on real vectors has some sort of vector pointer de-ref issue TBC

**Comment by getnamo** [comment]
feature pass in https://github.com/getnamo/Llama-Unreal/commit/435f5d93f5ed6860e98bbc945a79cb769b55e0f7.

Detailed tests pending before pushing release.

**Comment by getnamo** [comment]
Test results:
- Ingesting single documents or batch of documents now works.
- Retrieving chunks works and it is fast.

Thoughts:
- Need to manually setup embedding component and embedding mode on that component. 
- Need to setup and manually load the second llama component for the answering system (taking in chunks and answering quickly)
- Loading on startup doesn't work atm for llamacomponents? likely regression bug.
- We don't expose the chunk matching quality. We need to check how the retrieval logic can filter by quality of chunks (filter out bad chunks below x
- Ideally we'd setup a basic chunk fetch + answer with these chunks prompt + filter/etc all as a single call or utility system.

Pending UX updates we can probably move for a new release.

**Comment by getnamo** [comment]
Update:
- Encapsulated embedding model and answer model in a single RagStoreComponent allowing us to ingest and query with a full answer from the store without needing to inject the chunks manually
- added prefill support in 0.18.6 which is the final bit that makes the ragstore reliable.

Feature pending release.

**Comment by getnamo** [comment]
NB improvement note for later: dump irrelevant chunks and expose emptyish context for answer lookup. We need some sort of cutoff for quality of context.

**Comment by getnamo** [comment]
released in https://github.com/getnamo/Llama-Unreal/releases/tag/v1.0.0
